version: "3.6"
services:

  openindoor-db:
    image: postgis/postgis:12-3.1
    environment:
      POSTGRES_DB: openindoor-db
      POSTGRES_USER: openindoor-db-admin
      POSTGRES_PASSWORD: admin123
      API_URL: http://api-sandbox.openindoor.io
      APP_URL: http://app-sandbox.openindoor.io
    volumes:
    - ./test/data:/data
    # - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
    - 5432:5432