apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: openindoor
images:
  - name: openindoor/openindoor-db
    newTag: latest
  - name: openindoor/openindoor-adminer
    newTag: latest    
  - name: openindoor/openindoor-pgadmin
    newTag: latest    
resources:
- openindoor-db.yaml
- openindoor-adminer.yaml
- openindoor-pgadmin.yaml
