apiVersion: v1
kind: Service
metadata:
  name: openindoor-adminer
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: openindoor-adminer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: openindoor-adminer
  name: openindoor-adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      run: openindoor-adminer
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        run: openindoor-adminer
    spec:
      containers:
      - name: openindoor-adminer
        image: adminer:4
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: openindoor-db-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: openindoor-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openindoor-db-secret
              key: POSTGRES_PASSWORD  
        ports:
        - containerPort: 8080
