apiVersion: v1
kind: Service
metadata:
  name: openindoor-pgadmin
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: openindoor-pgadmin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openindoor-pgadmin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: openindoor-pgadmin
  name: openindoor-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openindoor-pgadmin
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: openindoor-pgadmin
    spec:
      containers:
      - name: openindoor-pgadmin
        image: dpage/pgadmin4
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: contact@openindoor.io
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin
        - name: PGADMIN_LISTEN_ADDRESS
          value: 0.0.0.0
        volumeMounts:
          - mountPath: /var/lib/pgadmin
            name: openindoor-pgadmin-storage
        ports:
        - containerPort: 80
      volumes:
        - name: openindoor-pgadmin-storage
          persistentVolumeClaim:
            claimName: openindoor-pgadmin-pvc
