apiVersion: v1
kind: Service
metadata:
  name: openindoor-db
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: openindoor-db
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: openindoor-db-secret
# type: Opaque
# data:
#   username: YWRtaW4=
#   password: MWYyZDFlMmU2N2Rm
---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: openindoor-db-config
# data:
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openindoor-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: openindoor-db
  name: openindoor-db
spec:
  replicas: 1
  selector:
    matchLabels:
      run: openindoor-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: openindoor-db
    spec:
      containers:
        - name: openindoor-db
          image: postgis/postgis:12-3.1
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: openindoor-db-secret
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: openindoor-db-secret
                  key: POSTGRES_DB        
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: openindoor-db-secret
                  key: POSTGRES_USER        
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openindoor-db-secret
                  key: POSTGRES_PASSWORD
            # - name: POSTGRES_DB
            #   value: openindoor-db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: openindoor-db-storage
      volumes:
        - name: openindoor-db-storage
          persistentVolumeClaim:
            claimName: openindoor-db-pvc
